# Generated by Django 5.1.4 on 2025-01-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_alter_accesscontrol_view_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrol',
            name='view_archive',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
